CREATE TABLE `households` (
	`id` text PRIMARY KEY NOT NULL,
	`purok` text NOT NULL,
	`block` text,
	`lot` text,
	`phase` text,
	`tenure_status` text,
	`housing_type` text,
	`construction_type` text,
	`sanitation_method` text,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE TABLE `residents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`full_name` text NOT NULL,
	`last_name` text,
	`first_name` text,
	`middle_name` text,
	`suffix` text,
	`birth_date` text,
	`gender` text,
	`civil_status` text,
	`religion` text,
	`contact_number` text,
	`email` text,
	`purok` text NOT NULL,
	`household_id` text,
	`is_head_of_household` integer DEFAULT false,
	`relationship_to_head` text,
	`educational_attainment` text,
	`occupation` text,
	`employment_status` text,
	`monthly_income` text,
	`source_of_livelihood` text,
	`is_pwd` integer DEFAULT false,
	`pwd_type` text,
	`is_senior_citizen` integer DEFAULT false,
	`is_resident_voter` integer DEFAULT false,
	`is_registered_voter` integer DEFAULT false,
	`is_single_parent` integer DEFAULT false,
	`is_ofw` integer DEFAULT false,
	`is_osy` integer DEFAULT false,
	`is_ip` integer DEFAULT false,
	`is_migrant` integer DEFAULT false,
	`is_national_pensioner` integer DEFAULT false,
	`is_local_pensioner` integer DEFAULT false,
	`debilitating_diseases` text,
	`is_bed_bound` integer DEFAULT false,
	`is_wheelchair_bound` integer DEFAULT false,
	`is_dialysis_patient` integer DEFAULT false,
	`is_cancer_patient` integer DEFAULT false,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE TABLE `settings` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL
);
