/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HouseholdsRouteImport } from './routes/households'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as DocumentMetricsRouteImport } from './routes/document-metrics'
import { Route as DistributionsRouteImport } from './routes/distributions'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsRoute = HouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentMetricsRoute = DocumentMetricsRouteImport.update({
  id: '/document-metrics',
  path: '/document-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionsRoute = DistributionsRouteImport.update({
  id: '/distributions',
  path: '/distributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/distributions': typeof DistributionsRoute
  '/document-metrics': typeof DocumentMetricsRoute
  '/extraction': typeof ExtractionRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/residents': typeof ResidentsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/distributions': typeof DistributionsRoute
  '/document-metrics': typeof DocumentMetricsRoute
  '/extraction': typeof ExtractionRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/residents': typeof ResidentsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/distributions': typeof DistributionsRoute
  '/document-metrics': typeof DocumentMetricsRoute
  '/extraction': typeof ExtractionRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/residents': typeof ResidentsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/distributions'
    | '/document-metrics'
    | '/extraction'
    | '/households'
    | '/import'
    | '/kiosk'
    | '/login'
    | '/monitor'
    | '/queue'
    | '/residents'
    | '/settings'
    | '/setup'
    | '/templates'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/distributions'
    | '/document-metrics'
    | '/extraction'
    | '/households'
    | '/import'
    | '/kiosk'
    | '/login'
    | '/monitor'
    | '/queue'
    | '/residents'
    | '/settings'
    | '/setup'
    | '/templates'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/distributions'
    | '/document-metrics'
    | '/extraction'
    | '/households'
    | '/import'
    | '/kiosk'
    | '/login'
    | '/monitor'
    | '/queue'
    | '/residents'
    | '/settings'
    | '/setup'
    | '/templates'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DistributionsRoute: typeof DistributionsRoute
  DocumentMetricsRoute: typeof DocumentMetricsRoute
  ExtractionRoute: typeof ExtractionRoute
  HouseholdsRoute: typeof HouseholdsRoute
  ImportRoute: typeof ImportRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  MonitorRoute: typeof MonitorRoute
  QueueRoute: typeof QueueRoute
  ResidentsRoute: typeof ResidentsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TemplatesRoute: typeof TemplatesRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households': {
      id: '/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof HouseholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-metrics': {
      id: '/document-metrics'
      path: '/document-metrics'
      fullPath: '/document-metrics'
      preLoaderRoute: typeof DocumentMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributions': {
      id: '/distributions'
      path: '/distributions'
      fullPath: '/distributions'
      preLoaderRoute: typeof DistributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DistributionsRoute: DistributionsRoute,
  DocumentMetricsRoute: DocumentMetricsRoute,
  ExtractionRoute: ExtractionRoute,
  HouseholdsRoute: HouseholdsRoute,
  ImportRoute: ImportRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  MonitorRoute: MonitorRoute,
  QueueRoute: QueueRoute,
  ResidentsRoute: ResidentsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TemplatesRoute: TemplatesRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
